config/routes.rb
Rails.application.routes.draw do
  get 'best', to: "cocktails#best", as: :best
  get 'game', to: "cocktails#game", as: :game
  get 'anagramme', to: "cocktails#anagramme", as: :anagramme
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

   resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, presence: true

  INGREDIENTS = [ "Sugar", "Lemon", "Mint", "Orange", "Ice" ]

  def rating_avg
    reviews.average(:rating).to_i
  end

end

app/models/cook.rb
class Cook < ApplicationRecord
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :description, presence: :true
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktail = Cocktail.new
    @doses = Dose.all
    @ingredients = Ingredient.all
    @all_ingredients = []
    @ingredients.each {|ingredient| @all_ingredients << ingredient.name}
    if params[:ingredient]
      return redirect_to cocktails_path unless params[:ingredient].in?(@all_ingredients)
      @ingredient = @ingredients.where(name: params[:ingredient])
      @doses = @doses.where(ingredient_id: @ingredient)
      @cocktails = Cocktail.all
    else
      @cocktails = Cocktail.all
    end
  end

  def game; end

  def best
    @cocktails = Cocktail.joins(:reviews).group('cocktails.id').having('AVG(reviews.rating) >= 3')
    @reviews = Review.all
    @reviews = @reviews.where(:rating => [3])
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @reviews = Review.all
    @reviews = @reviews.where(cocktail_id: params[:id])
    @doses = Dose.all
    @doses = @doses.includes(:ingredient).where(cocktail_id: params[:id])
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save!
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktails = Cocktail.find(params[:id])
    @cocktails.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      redirect_to cocktail_path(@cocktail)
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    @review.save!
    redirect_to cocktail_path(@cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://goo.gl/yMPjbc');">
  <div class="banner-content">
    <h1><%= var1 %></h1>
  </div>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |c| %>
  <%= c.input :name %>
  <%= c.button :submit, class: "btn btn-block btn-primary" %>
<% end %>

app/views/cocktails/best.html.erb
<div class="container">
  <h1>Cocktails with ingredient in params</h1>
  <div class="row">
    <% @cocktails.each do |cocktail|  %>
      <div class="col-xs-6 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://goo.gl/PYcd8K');">
          <div class="card-description">
             <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          </div> <!-- end of card-description -->
          <div class="card-rating">
            <% cocktail.rating_avg.times do %>
              <i class='fa fa-star' style="color: #F9C72E;"></i>
            <% end %>
            <% (5-cocktail.rating_avg).times do %>
              <i class='fa fa-star' style="color: #CCCCCC;"></i>
            <% end %>
          </div>
        </div> <!-- end of card -->
      </div>
    <% end %>
  </div>
  <%= link_to "Back to all cocktails", cocktails_path %>
</div>

app/views/cocktails/game.html.erb
<h1 class="text-center">Race, who's gonna win ?</h1>
<h3 class="text-center">Press "c" for <%= image_tag "player_1.png", alt: "cocktail" %> - Press "b" for <%= image_tag "player_2.png", alt: "beer" %></h3>
    <hr>
    <!-- You race HTML code here -->
    <div class="container">
      <table class="racer_table">
        <tr id="cocktail_race">
          <td class="active"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="arrivee"></td>
        </tr>
        <tr id="beer_race">
          <td class="active"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="arrivee"></td>
        </tr>
      </table>
    </div>

    <hr>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="cocktail-header">
    <h1>List of all cocktails</h1>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm"  style = "margin-left: 15px;">
      Add a Cocktail
    </button>
    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <%= render 'form', cocktail: @cocktail %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if params[:ingredient].nil? %>
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-6 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://goo.gl/PYcd8K');">
            <div class="card-category">
              <%= link_to icon('far', 'times-circle'), cocktail_path(cocktail.id), method: :delete, data: {confirm: "sure?"}   %>
            </div>
            <div class="card-description">
              <h2><%= link_to cocktail.name, cocktail_path(cocktail.id) %></h2>
            </div>
            <div class="card-rating">
              <div class="jaune">
                <% cocktail.rating_avg.times do %>
                  <!-- <i class='fa fa-star' style="color: #F9C72E;"></i> -->
                  <%= link_to icon('fa', 'star'), "#", style:"color: #F9C72E;" %>
                <% end %>
              </div>
              <div class="grey">
                <% (5-cocktail.rating_avg).times do %>
                  <%= link_to icon('fa', 'star'), "#", style:"color: #CCCCCC;" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <% @doses.each do |dose|  %>
        <div class="col-xs-6 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://goo.gl/PYcd8K');">
            <div class="card-category">
              <%= link_to icon('far', 'times-circle'), cocktail_path(dose.cocktail_id), method: :delete, data: {confirm: "sure?"}   %>
            </div>
            <div class="card-description">
               <h2><%= link_to dose.cocktail.name, cocktail_path(dose.cocktail_id) %></h2>
            </div> <!-- end of card-description -->
            <div class="card-rating">
              <% dose.cocktail.rating_avg.times do %>
                <i class='fa fa-star' style="color: #F9C72E;"></i>
              <% end %>
              <% (5-dose.cocktail.rating_avg).times do %>
                <i class='fa fa-star' style="color: #CCCCCC;"></i>
              <% end %>
            </div>
          </div> <!-- end of card -->
        </div>
      <% end %>
    <% end %>
  <%= link_to "Back to all cocktails", cocktails_path %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<%= render 'banner', var1:@cocktail.name%>

<div class="container">

  <h1>Recipe</h1>
  <p><%= link_to "Back to cocktails", cocktails_path  %></p>

  <div class="cocktail-infos">

    <div class="receipe">
      <table>
        <tr>
          <th>Ingredient</th>
          <th>Description</th>
          <th>Delete ?</th>
        </tr>
        <% @cocktail.doses.each do |dose| %>
          <tr>
            <td><%= dose.ingredient.name %></td>
            <td><%= dose.description %></td>
            <td><%= link_to icon('far', 'times-circle'), dose_path(dose), method: :delete, data: {confirm: "sure?"} %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="options">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm"  style = "margin-left: 15px;">
        Add a Dose ?
      </button>
      <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm" role="document">
          <div class="modal-content">
            <%= render 'doses/form', cocktail: @cocktail, dose: @dose %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="reviews">
    <h1>Reviews</h1>
    <% @reviews.each do |review| %>
      <%= review.description %>
      <% review.rating.times do %>
        <i class='fa fa-star' style="color: #F9C72E;"></i>
      <% end %>
      <% (5 - review.rating).times do %>
        <i class='fa fa-star' style="color: #CCCCCC;"></i>
      <%=  %>
      <% end %>
    <% end %>
  </div>
  <div class="review">
    <%= link_to "Add a review", cocktail_path(@cocktail) %>
    <%= render 'reviews/form', cocktail:@cocktail, review:@review %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for([cocktail, dose]) do |c| %>
  <%= c.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= c.input :description %>
  <%= c.button :submit, class: "btn btn-block btn-primary" %>
<% end %>

app/views/doses/_new.html.erb
<h1>this is where you are redirected if your form is not valid</h1>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-brand">

  <%= link_to image_tag('logo.png'), cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <div class="navbar-wagon-right">
      <%= link_to "Best Cocktails", best_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Play a game", game_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
  <div class="navbar-wagon-item">
      <div class="dropdown">
  <!--       <img src="https://kitt.lewagon.com/placeholder/users/martingalle" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
        <div class="navbar-wagon-item navbar-wagon-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink">By ingredient<span class="caret"></span></div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% Ingredient.all.each do |ingredient| %>
              <li><%= link_to ingredient.name.capitalize, cocktails_path(ingredient: ingredient.name), class: "navbar-wagon-item navbar-wagon-link" %></li>
            <% end %>
          </ul>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([cocktail, review]) do |d| %>
  <%= d.input :description %>
  <%= d.input :rating %>
  <%= d.button :submit, class: "btn btn-block btn-primary" %>
<% end %>